package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * AlbumTrack generated by hbm2java
 */
public class AlbumTrack implements java.io.Serializable {

	private AlbumTrackId id;
	private BigDecimal length;
	private String fileLocation;
	private Date lastUpdateTs;

	public AlbumTrack() {
	}

	public AlbumTrack(AlbumTrackId id, BigDecimal length, String fileLocation,
			Date lastUpdateTs) {
		this.id = id;
		this.length = length;
		this.fileLocation = fileLocation;
		this.lastUpdateTs = lastUpdateTs;
	}

	public AlbumTrackId getId() {
		return this.id;
	}

	public void setId(AlbumTrackId id) {
		this.id = id;
	}

	public BigDecimal getLength() {
		return this.length;
	}

	public void setLength(BigDecimal length) {
		this.length = length;
	}

	public String getFileLocation() {
		return this.fileLocation;
	}

	public void setFileLocation(String fileLocation) {
		this.fileLocation = fileLocation;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
