package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * AlbumApprovalStatus generated by hbm2java
 */
public class AlbumApprovalStatus implements java.io.Serializable {

	private Integer approvalStatusCode;
	private String description;
	private Date lastUpdatedTs;

	public AlbumApprovalStatus() {
	}

	public AlbumApprovalStatus(String description, Date lastUpdatedTs) {
		this.description = description;
		this.lastUpdatedTs = lastUpdatedTs;
	}

	public Integer getApprovalStatusCode() {
		return this.approvalStatusCode;
	}

	public void setApprovalStatusCode(Integer approvalStatusCode) {
		this.approvalStatusCode = approvalStatusCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLastUpdatedTs() {
		return this.lastUpdatedTs;
	}

	public void setLastUpdatedTs(Date lastUpdatedTs) {
		this.lastUpdatedTs = lastUpdatedTs;
	}

}
