package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * AlbumReview generated by hbm2java
 */
public class AlbumReview implements java.io.Serializable {

	private Long reviewId;
	private long albumId;
	private long memberId;
	private String albumReview;
	private Date lastUpdateTs;

	public AlbumReview() {
	}

	public AlbumReview(long albumId, long memberId, String albumReview,
			Date lastUpdateTs) {
		this.albumId = albumId;
		this.memberId = memberId;
		this.albumReview = albumReview;
		this.lastUpdateTs = lastUpdateTs;
	}

	public Long getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Long reviewId) {
		this.reviewId = reviewId;
	}

	public long getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(long albumId) {
		this.albumId = albumId;
	}

	public long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(long memberId) {
		this.memberId = memberId;
	}

	public String getAlbumReview() {
		return this.albumReview;
	}

	public void setAlbumReview(String albumReview) {
		this.albumReview = albumReview;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
