package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * ArtistLabel generated by hbm2java
 */
public class ArtistLabel implements java.io.Serializable {

	private Integer labelId;
	private String labelName;
	private String labelWebSite;
	private String labelPhoneNumber;
	private String labelStreetAddress;
	private String labelState;
	private String labelZipCode;
	private int labelCountryCode;
	private Date lastUpdateTs;

	public ArtistLabel() {
	}

	public ArtistLabel(String labelName, String labelWebSite,
			String labelPhoneNumber, String labelStreetAddress,
			String labelState, String labelZipCode, int labelCountryCode,
			Date lastUpdateTs) {
		this.labelName = labelName;
		this.labelWebSite = labelWebSite;
		this.labelPhoneNumber = labelPhoneNumber;
		this.labelStreetAddress = labelStreetAddress;
		this.labelState = labelState;
		this.labelZipCode = labelZipCode;
		this.labelCountryCode = labelCountryCode;
		this.lastUpdateTs = lastUpdateTs;
	}

	public Integer getLabelId() {
		return this.labelId;
	}

	public void setLabelId(Integer labelId) {
		this.labelId = labelId;
	}

	public String getLabelName() {
		return this.labelName;
	}

	public void setLabelName(String labelName) {
		this.labelName = labelName;
	}

	public String getLabelWebSite() {
		return this.labelWebSite;
	}

	public void setLabelWebSite(String labelWebSite) {
		this.labelWebSite = labelWebSite;
	}

	public String getLabelPhoneNumber() {
		return this.labelPhoneNumber;
	}

	public void setLabelPhoneNumber(String labelPhoneNumber) {
		this.labelPhoneNumber = labelPhoneNumber;
	}

	public String getLabelStreetAddress() {
		return this.labelStreetAddress;
	}

	public void setLabelStreetAddress(String labelStreetAddress) {
		this.labelStreetAddress = labelStreetAddress;
	}

	public String getLabelState() {
		return this.labelState;
	}

	public void setLabelState(String labelState) {
		this.labelState = labelState;
	}

	public String getLabelZipCode() {
		return this.labelZipCode;
	}

	public void setLabelZipCode(String labelZipCode) {
		this.labelZipCode = labelZipCode;
	}

	public int getLabelCountryCode() {
		return this.labelCountryCode;
	}

	public void setLabelCountryCode(int labelCountryCode) {
		this.labelCountryCode = labelCountryCode;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
