package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * Artist generated by hbm2java
 */
public class Artist implements java.io.Serializable {

	private Long artistId;
	private long memberId;
	private String artistName;
	private String artistProfileAddress;
	private long labelId;
	private long genreId;
	private String artistBio;
	private String artistFanPage;
	private Date lastUpdateTs;

	public Artist() {
	}

	public Artist(long memberId, String artistName,
			String artistProfileAddress, long labelId, long genreId,
			String artistBio, String artistFanPage, Date lastUpdateTs) {
		this.memberId = memberId;
		this.artistName = artistName;
		this.artistProfileAddress = artistProfileAddress;
		this.labelId = labelId;
		this.genreId = genreId;
		this.artistBio = artistBio;
		this.artistFanPage = artistFanPage;
		this.lastUpdateTs = lastUpdateTs;
	}

	public Long getArtistId() {
		return this.artistId;
	}

	public void setArtistId(Long artistId) {
		this.artistId = artistId;
	}

	public long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(long memberId) {
		this.memberId = memberId;
	}

	public String getArtistName() {
		return this.artistName;
	}

	public void setArtistName(String artistName) {
		this.artistName = artistName;
	}

	public String getArtistProfileAddress() {
		return this.artistProfileAddress;
	}

	public void setArtistProfileAddress(String artistProfileAddress) {
		this.artistProfileAddress = artistProfileAddress;
	}

	public long getLabelId() {
		return this.labelId;
	}

	public void setLabelId(long labelId) {
		this.labelId = labelId;
	}

	public long getGenreId() {
		return this.genreId;
	}

	public void setGenreId(long genreId) {
		this.genreId = genreId;
	}

	public String getArtistBio() {
		return this.artistBio;
	}

	public void setArtistBio(String artistBio) {
		this.artistBio = artistBio;
	}

	public String getArtistFanPage() {
		return this.artistFanPage;
	}

	public void setArtistFanPage(String artistFanPage) {
		this.artistFanPage = artistFanPage;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
