package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * ArtistGenre generated by hbm2java
 */
public class ArtistGenre implements java.io.Serializable {

	private long genreId;
	private String genreDesc;
	private Long parentGenreId;
	private Date lastUpdateTs;

	public ArtistGenre() {
	}

	public ArtistGenre(long genreId, String genreDesc, Date lastUpdateTs) {
		this.genreId = genreId;
		this.genreDesc = genreDesc;
		this.lastUpdateTs = lastUpdateTs;
	}

	public ArtistGenre(long genreId, String genreDesc, Long parentGenreId,
			Date lastUpdateTs) {
		this.genreId = genreId;
		this.genreDesc = genreDesc;
		this.parentGenreId = parentGenreId;
		this.lastUpdateTs = lastUpdateTs;
	}

	public long getGenreId() {
		return this.genreId;
	}

	public void setGenreId(long genreId) {
		this.genreId = genreId;
	}

	public String getGenreDesc() {
		return this.genreDesc;
	}

	public void setGenreDesc(String genreDesc) {
		this.genreDesc = genreDesc;
	}

	public Long getParentGenreId() {
		return this.parentGenreId;
	}

	public void setParentGenreId(Long parentGenreId) {
		this.parentGenreId = parentGenreId;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
