package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * Carrier generated by hbm2java
 */
public class Carrier implements java.io.Serializable {

	private Integer carrierId;
	private int carrierName;
	private String carrierTrackingSite;
	private int carrierStatus;
	private String carrierPhoneNumber;
	private Date lastUpdateTs;

	public Carrier() {
	}

	public Carrier(int carrierName, String carrierTrackingSite,
			int carrierStatus, String carrierPhoneNumber, Date lastUpdateTs) {
		this.carrierName = carrierName;
		this.carrierTrackingSite = carrierTrackingSite;
		this.carrierStatus = carrierStatus;
		this.carrierPhoneNumber = carrierPhoneNumber;
		this.lastUpdateTs = lastUpdateTs;
	}

	public Integer getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(Integer carrierId) {
		this.carrierId = carrierId;
	}

	public int getCarrierName() {
		return this.carrierName;
	}

	public void setCarrierName(int carrierName) {
		this.carrierName = carrierName;
	}

	public String getCarrierTrackingSite() {
		return this.carrierTrackingSite;
	}

	public void setCarrierTrackingSite(String carrierTrackingSite) {
		this.carrierTrackingSite = carrierTrackingSite;
	}

	public int getCarrierStatus() {
		return this.carrierStatus;
	}

	public void setCarrierStatus(int carrierStatus) {
		this.carrierStatus = carrierStatus;
	}

	public String getCarrierPhoneNumber() {
		return this.carrierPhoneNumber;
	}

	public void setCarrierPhoneNumber(String carrierPhoneNumber) {
		this.carrierPhoneNumber = carrierPhoneNumber;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
