package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * CountryCode generated by hbm2java
 */
public class CountryCode implements java.io.Serializable {

	private Integer countryId;
	private String countryName;
	private Date lastUpdateTs;

	public CountryCode() {
	}

	public CountryCode(String countryName, Date lastUpdateTs) {
		this.countryName = countryName;
		this.lastUpdateTs = lastUpdateTs;
	}

	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
