package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * DeliveryStatus generated by hbm2java
 */
public class DeliveryStatus implements java.io.Serializable {

	private int deliveryStatusCode;
	private String deliveryStatusDescription;
	private Date lastUpdateTs;

	public DeliveryStatus() {
	}

	public DeliveryStatus(int deliveryStatusCode,
			String deliveryStatusDescription, Date lastUpdateTs) {
		this.deliveryStatusCode = deliveryStatusCode;
		this.deliveryStatusDescription = deliveryStatusDescription;
		this.lastUpdateTs = lastUpdateTs;
	}

	public int getDeliveryStatusCode() {
		return this.deliveryStatusCode;
	}

	public void setDeliveryStatusCode(int deliveryStatusCode) {
		this.deliveryStatusCode = deliveryStatusCode;
	}

	public String getDeliveryStatusDescription() {
		return this.deliveryStatusDescription;
	}

	public void setDeliveryStatusDescription(String deliveryStatusDescription) {
		this.deliveryStatusDescription = deliveryStatusDescription;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
