package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * MediaComment generated by hbm2java
 */
public class MediaComment implements java.io.Serializable {

	private Long mediaCommentId;
	private long mediaId;
	private long memberId;
	private String comment;
	private Date lastUpdateTs;

	public MediaComment() {
	}

	public MediaComment(long mediaId, long memberId, String comment,
			Date lastUpdateTs) {
		this.mediaId = mediaId;
		this.memberId = memberId;
		this.comment = comment;
		this.lastUpdateTs = lastUpdateTs;
	}

	public Long getMediaCommentId() {
		return this.mediaCommentId;
	}

	public void setMediaCommentId(Long mediaCommentId) {
		this.mediaCommentId = mediaCommentId;
	}

	public long getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(long mediaId) {
		this.mediaId = mediaId;
	}

	public long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(long memberId) {
		this.memberId = memberId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
