package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * MediaTag generated by hbm2java
 */
public class MediaTag implements java.io.Serializable {

	private Long mediaTagId;
	private long mediaId;
	private long memberId;
	private long taggedMemberId;
	private Date lastUpdateTs;

	public MediaTag() {
	}

	public MediaTag(long mediaId, long memberId, long taggedMemberId,
			Date lastUpdateTs) {
		this.mediaId = mediaId;
		this.memberId = memberId;
		this.taggedMemberId = taggedMemberId;
		this.lastUpdateTs = lastUpdateTs;
	}

	public Long getMediaTagId() {
		return this.mediaTagId;
	}

	public void setMediaTagId(Long mediaTagId) {
		this.mediaTagId = mediaTagId;
	}

	public long getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(long mediaId) {
		this.mediaId = mediaId;
	}

	public long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(long memberId) {
		this.memberId = memberId;
	}

	public long getTaggedMemberId() {
		return this.taggedMemberId;
	}

	public void setTaggedMemberId(long taggedMemberId) {
		this.taggedMemberId = taggedMemberId;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
