package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * MemberEducation generated by hbm2java
 */
public class MemberEducation implements java.io.Serializable {

	private long memberId;
	private int educationType;
	private String name;
	private int yearStarted;
	private int yearLeft;
	private int degreeEarnedType;
	private Date lastUpdateTs;

	public MemberEducation() {
	}

	public MemberEducation(long memberId, int educationType, String name,
			int yearStarted, int yearLeft, int degreeEarnedType,
			Date lastUpdateTs) {
		this.memberId = memberId;
		this.educationType = educationType;
		this.name = name;
		this.yearStarted = yearStarted;
		this.yearLeft = yearLeft;
		this.degreeEarnedType = degreeEarnedType;
		this.lastUpdateTs = lastUpdateTs;
	}

	public long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(long memberId) {
		this.memberId = memberId;
	}

	public int getEducationType() {
		return this.educationType;
	}

	public void setEducationType(int educationType) {
		this.educationType = educationType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getYearStarted() {
		return this.yearStarted;
	}

	public void setYearStarted(int yearStarted) {
		this.yearStarted = yearStarted;
	}

	public int getYearLeft() {
		return this.yearLeft;
	}

	public void setYearLeft(int yearLeft) {
		this.yearLeft = yearLeft;
	}

	public int getDegreeEarnedType() {
		return this.degreeEarnedType;
	}

	public void setDegreeEarnedType(int degreeEarnedType) {
		this.degreeEarnedType = degreeEarnedType;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
