package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * SaleItem generated by hbm2java
 */
public class SaleItem implements java.io.Serializable {

	private SaleItemId id;
	private int itemType;
	private float itemPrice;
	private float itemQty;
	private int itemDeliveryStatus;
	private int itemDeliveryType;
	private Date lastUpdateTs;

	public SaleItem() {
	}

	public SaleItem(SaleItemId id, int itemType, float itemPrice,
			float itemQty, int itemDeliveryStatus, int itemDeliveryType,
			Date lastUpdateTs) {
		this.id = id;
		this.itemType = itemType;
		this.itemPrice = itemPrice;
		this.itemQty = itemQty;
		this.itemDeliveryStatus = itemDeliveryStatus;
		this.itemDeliveryType = itemDeliveryType;
		this.lastUpdateTs = lastUpdateTs;
	}

	public SaleItemId getId() {
		return this.id;
	}

	public void setId(SaleItemId id) {
		this.id = id;
	}

	public int getItemType() {
		return this.itemType;
	}

	public void setItemType(int itemType) {
		this.itemType = itemType;
	}

	public float getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(float itemPrice) {
		this.itemPrice = itemPrice;
	}

	public float getItemQty() {
		return this.itemQty;
	}

	public void setItemQty(float itemQty) {
		this.itemQty = itemQty;
	}

	public int getItemDeliveryStatus() {
		return this.itemDeliveryStatus;
	}

	public void setItemDeliveryStatus(int itemDeliveryStatus) {
		this.itemDeliveryStatus = itemDeliveryStatus;
	}

	public int getItemDeliveryType() {
		return this.itemDeliveryType;
	}

	public void setItemDeliveryType(int itemDeliveryType) {
		this.itemDeliveryType = itemDeliveryType;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
