package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * SaleStatus generated by hbm2java
 */
public class SaleStatus implements java.io.Serializable {

	private Integer saleStatusCode;
	private String saleStatusDescription;
	private Date lastUpdateTs;

	public SaleStatus() {
	}

	public SaleStatus(String saleStatusDescription, Date lastUpdateTs) {
		this.saleStatusDescription = saleStatusDescription;
		this.lastUpdateTs = lastUpdateTs;
	}

	public Integer getSaleStatusCode() {
		return this.saleStatusCode;
	}

	public void setSaleStatusCode(Integer saleStatusCode) {
		this.saleStatusCode = saleStatusCode;
	}

	public String getSaleStatusDescription() {
		return this.saleStatusDescription;
	}

	public void setSaleStatusDescription(String saleStatusDescription) {
		this.saleStatusDescription = saleStatusDescription;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
