package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * Sale generated by hbm2java
 */
public class Sale implements java.io.Serializable {

	private Long saleId;
	private long memberId;
	private Date ordDate;
	private Date shpDate;
	private int saleStatus;
	private Date expectedArrivalDate;
	private String trackingNumber;
	private Integer carrierId;
	private int paymentType;
	private Date lastUpdateTs;

	public Sale() {
	}

	public Sale(long memberId, Date ordDate, int saleStatus, int paymentType,
			Date lastUpdateTs) {
		this.memberId = memberId;
		this.ordDate = ordDate;
		this.saleStatus = saleStatus;
		this.paymentType = paymentType;
		this.lastUpdateTs = lastUpdateTs;
	}

	public Sale(long memberId, Date ordDate, Date shpDate, int saleStatus,
			Date expectedArrivalDate, String trackingNumber, Integer carrierId,
			int paymentType, Date lastUpdateTs) {
		this.memberId = memberId;
		this.ordDate = ordDate;
		this.shpDate = shpDate;
		this.saleStatus = saleStatus;
		this.expectedArrivalDate = expectedArrivalDate;
		this.trackingNumber = trackingNumber;
		this.carrierId = carrierId;
		this.paymentType = paymentType;
		this.lastUpdateTs = lastUpdateTs;
	}

	public Long getSaleId() {
		return this.saleId;
	}

	public void setSaleId(Long saleId) {
		this.saleId = saleId;
	}

	public long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(long memberId) {
		this.memberId = memberId;
	}

	public Date getOrdDate() {
		return this.ordDate;
	}

	public void setOrdDate(Date ordDate) {
		this.ordDate = ordDate;
	}

	public Date getShpDate() {
		return this.shpDate;
	}

	public void setShpDate(Date shpDate) {
		this.shpDate = shpDate;
	}

	public int getSaleStatus() {
		return this.saleStatus;
	}

	public void setSaleStatus(int saleStatus) {
		this.saleStatus = saleStatus;
	}

	public Date getExpectedArrivalDate() {
		return this.expectedArrivalDate;
	}

	public void setExpectedArrivalDate(Date expectedArrivalDate) {
		this.expectedArrivalDate = expectedArrivalDate;
	}

	public String getTrackingNumber() {
		return this.trackingNumber;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	public Integer getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(Integer carrierId) {
		this.carrierId = carrierId;
	}

	public int getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(int paymentType) {
		this.paymentType = paymentType;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
