package com.burtona.db.model;

// Generated Apr 17, 2011 3:58:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * SaleItemType generated by hbm2java
 */
public class SaleItemType implements java.io.Serializable {

	private int typeCode;
	private String typeDescription;
	private Date lastUpdateTs;

	public SaleItemType() {
	}

	public SaleItemType(int typeCode, String typeDescription, Date lastUpdateTs) {
		this.typeCode = typeCode;
		this.typeDescription = typeDescription;
		this.lastUpdateTs = lastUpdateTs;
	}

	public int getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(int typeCode) {
		this.typeCode = typeCode;
	}

	public String getTypeDescription() {
		return this.typeDescription;
	}

	public void setTypeDescription(String typeDescription) {
		this.typeDescription = typeDescription;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
